var patents = [
	{
		"title":"基于层恢复敏感度的分级剪枝率方法.",
		"author":"李超,杨康,严阳春.",
		"highlight_author":"李超",
		"number":"202010230969.3."
	},
	{
		"title":"一种基于相关权重评估的可解释方法.",
		"author":"李超,刁博宇.",
		"highlight_author":"李超",
		"number":"202018002671.8."
	},
	{
		"title":"一种用于深度神经网络交互信息量化的方法.",
		"author":"李超,刁博宇.",
		"highlight_author":"李超",
		"number":"202010558767.1."
	},
	{
		"title":"一种用于点云目标检测模型的压缩方法.",
		"author":"李超,孙飞.",
		"highlight_author":"李超",
		"number":"202010243264.5."
	},
	{
		"title":"一种用于压缩深度神经网络模型的方法和系统.",
		"author":"李超,许建荣,崔碧峰,宫禄齐.",
		"highlight_author":"李超",
		"number":"202110234699.8."
	},
	{
		"title":"一种适用于具有重叠视野的摄像机网络下的目标追踪方法.",
		"author":"李超,荆月青.",
		"highlight_author":"李超",
		"number":"ZL202111410923.0."
	},
	{
		"title":"基于预训练模型的多模态知识图谱表征系统及方法.",
		"author":"李超,张钊,姚远舟.",
		"highlight_author":"李超",
		"number":"ZL202210980815.5."
	},
	{
		"title":"一种无人系统分布式一致性编队控制方法及其系统.",
		"author":"李超,徐勇军,安竹林,唐宏.",
		"highlight_author":"李超",
		"number":"201310320211.9."
	},
	{
		"title":"一种水下传感网媒体介质访问控制方法.",
		"author":"李超,徐勇军,安竹林,李晓维.",
		"highlight_author":"李超",
		"number":"201510011817.3."
	},
	{
		"title":"水下传感网的媒体介质访问控制协议方法及系统.",
		"author":"李超,徐勇军,安竹林,李晓维.",
		"highlight_author":"李超",
		"number":"201410265061.0."
	},
	{
		"title":"一种基于水下传感网的自适应媒体访问控制方法及其系统.",
		"author":" 李超,徐勇军,安竹林,李晓维.",
		"highlight_author":"李超",
		"number":"201410164030.6."
	},
	{
		"title":"适用于水下传感网的媒体访问控制方法及系统.",
		"author":"李超,徐勇军,安竹林,李晓维.",
		"highlight_author":"李超",
		"number":"201410300914.X."
	},
	{
		"title":"基于语义分形的可解释GAN的图像生成训练方法及装置.",
		"author":"李超,王劲.",
		"highlight_author":"李超",
		"number":"202211373030.8."
	},
	{
		"title":"基于推理模式评估深伪图像检测模型泛化性方法及装置.",
		"author":"李超,姚柯璐.",
		"highlight_author":"李超",
		"number":"ZL202211395358.X."
	},
	{
		"title":"基于层次注意力图神经网络的数据信息推荐方法和装置.",
		"author":"李超,张钊,李其明.",
		"highlight_author":"李超",
		"number":"ZL202210541192.1."
	},
	{
		"title":"基于CPU-GPU异构并行的地表形变反演方法与系统.王京.",
		"author":"李超,刁博宇,黄智华,胡泽辰,郑新千.",
		"highlight_author":"李超",
		"number":"ZL202210734885.2."
	},
	{
		"title":"面向应急条件下多遥感卫星观测任务调度的方法和装置.",
		"author":"刁博宇,李国邦,许宇栋,李超.",
		"highlight_author":"李超",
		"number":"202210856415.3."
	},
	{
		"title":"基于Transformer的InSAR技术冻土区多变量时序形变预测方法及装置.",
		"author":"王京,李超,刁博宇,黄智华,胡泽辰.",
		"highlight_author":"李超",
		"number":"202210844540.2."
	},
	{
		"title":"一种面向I/Q信号识别的半监督宽度学习方法及装置.",
		"author":"韩光洁,徐政伟,李超.",
		"highlight_author":"李超",
		"number":"202211341465.4."
	},
	{
		"title":"一种边缘数据管理方法、介质、边缘服务器和系统.",
		"author":"刁博宇,李超,徐勇军,赵二虎.",
		"highlight_author":"李超",
		"number":"202010588987.9."
	},
	{
		"title":"用于人工智能处理器的数据互联方法、系统、芯片和装置.",
		"author":"赵二虎,徐勇军,吴济文,安竹林,李超.",
		"highlight_author":"李超",
		"number":"201910826850.X."
	},
	{
		"title":"一种适用于长延迟SIC网络的链路调度方法和系统.",
		"author":"徐亦达,李超,徐勇军,刁博宇,王琪,安竹林.",
		"highlight_author":"李超",
		"number":"201710917120.1."
	}
	
]