var students = [
	{
		"name":"姚柯璐",
		"img":"./img/ykl.png",
		"start_year":"2024",
		"type":"博士",
		"email":"yaokelu@zhejianglab.org",
		"homepage":""
	},
	{
		"name":"李贤",
		"img":"./img/lx.jpg",
		"start_year":"2024",
		"type":"博士",
		"email":"xianlee@zju.edu.cn",
		"homepage":""
	},
	{
		"name":"陈雅莹",
		"img":"./img/female.jpg",
		"start_year":"2024",
		"type":"博士",
		"email":"12421264@zju.edu.cn",
		"homepage":""
	},
	{
		"name":"吕程辉",
		"img":"./img/lch.jpg",
		"start_year":"2023",
		"type":"硕士",
		"email":"lvchenghui23@mails.ucas.ac.cn",
		"homepage":""
	},
	{
		"name":"王劲",
		"img":"./img/wj.jpg",
		"start_year":"2019",
		"type":"硕士",
		"email":"wangjing@mails.ucas.ac.cn",
		"homepage":""
	}
]